### ISSUE TITLE
output flashes every time it refreshes

### ISSUE THREAD

**Issue by bpenda** [nagracks/git_log_viewer#3]
Is this normal? It's really distracting.

**Comment by bpenda** [comment]
also got this error after running it for a few minutes on a mac: Traceback (most recent call last):
  File "/usr/local/bin/log_viewer.py", line 104, in <module>
    main()
  File "/usr/local/bin/log_viewer.py", line 97, in main
    print output_string.format(show_commits=show_commits(count),
  File "/usr/local/bin/log_viewer.py", line 50, in show_commits
    stderr=PIPE)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1227, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1179, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files

**Comment by nagracks** [comment]
Yeah, I am woking on it. Thanx
